remote_theme: just-the-docs/just-the-docs@v0.4.2

title: Documentation
description: ThreatWinds documentation for developers and advanced users.

logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"
color_scheme: blueTheme

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

callouts:
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

aux_links:
  Git: https://github.com/ThreatWinds/Documentation
  Blog: https://developers.threatwinds.com
  Support: https://support.threatwinds.com