theme: just-the-docs

title: Documentation
description: ThreatWinds documentation for developers and advanced users.

logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: blueTheme

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

aux_links:
  App: https://threatwinds.com
  Roadmap: https://github.com/orgs/threatwinds/projects/2/views/3
  Support: https://support.threatwinds.com/help/1606218418
  Developers Center: https://developers.threatwinds.com

ga_tracking: G-S1QNNPZWEM
ga_tracking_anonymize_ip: false
